[project]
name = "conquest2a"
version = "0.4.0"
authors = [{ name = "Chung", email = "dev.chpxu@outlook.com" }]
description = "A Python utility that deals with some pre- and post-processing functions for the linear scaling DFT program, CONQUEST."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "numpy>=2.0.0",
  "scipy>=1.10.0",
  "ase",
  "matplotlib>=3.11",
  "scienceplots>=2.2.2",
]
[project.urls]
Homepage = "https://github.com/chpxu/CONQUEST_TO_VASP"
Issues = "https://github.com/chpxu/CONQUEST_TO_VASP/issues"

[tool.basedpyright]
extraPaths = ["."]
include = ["conquest2a"]
exclude = [
  "**/node_modules",
  "**/__pycache__",
  "**/.direnv",
  "**/.github",
  "**/*_cache",
]
reportUnusedCallResult = false
reportMissingImports = "warning"
reportPrivateImportUsage = false
reportMissingTypeStubs = false
reportMissingModuleSource = false
reportAny = false
reportExplicitAny = false
pythonVersion = "3.13"
pythonPlatform = "Linux"

executionEnvironments = [
  { root = "conquest2a/tests", reportPrivateUsage = false },
  { root = "conquest2a" },
]

[tool.mypy]
strict = true
disallow_any_generics = true
disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_ignores = false
untyped_calls_exclude = ["ase"]

[[tool.mypy.overrides]]
disable_error_code = [
  # "abstract",
  # "arg-type",
  # "assignment",
  # "attr-defined",
  # "call-arg",
  "import-not-found",
  # "index",
  # "list-item",
  # "misc",
  # "name-defined",
  # "no-redef",
  # "operator",
  # "override",
  # "return-value",
  # "return",
  # "syntax",
  "unused-ignore",
  "ignore-without-code",
  # "union-attr",
  # "var-annotated",
]
module = ["nest_asyncio.*", "requests.*"]

[tool.black]
line-length = 100
target-version = ['py311', 'py312', 'py313', 'py314']
force-exclude = '''
(
   ^/.*_pb2\.py$
  | .*_pb2.py
  | .nix*
  | _nix*
  | conquest2a/elements\.txt$
)
'''

[build-system]
requires = ["hatchling>=1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
packages = ["conquest2a"]

[tool.hatch.build.targets.wheel]
packages = ["conquest2a"]
